basePath: /api/v1
definitions:
  auth.ApiError:
    properties:
      field:
        type: string
      msg:
        type: string
    type: object
  auth.registerForm:
    properties:
      email:
        type: string
      password:
        maxLength: 50
        minLength: 3
        type: string
    required:
    - email
    - password
    type: object
  auth.tokenResponse:
    properties:
      code:
        type: integer
      expire:
        type: string
      token:
        type: string
    type: object
  user.errorResponse:
    properties:
      code:
        type: integer
      message:
        type: string
    type: object
  user.userResponse:
    properties:
      email:
        type: string
      userID:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server celler server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Photoclub API
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: Login user
      parameters:
      - description: register form
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/auth.registerForm'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/auth.tokenResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/auth.ApiError'
      security:
      - ApiKeyAuth: []
      summary: Auth
      tags:
      - Auth
  /auth/refresh_token:
    get:
      description: Refresh user login token
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/auth.tokenResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/auth.ApiError'
      security:
      - ApiKeyAuth: []
      summary: Auth
      tags:
      - Auth
  /auth/register:
    post:
      description: register user
      parameters:
      - description: register form
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/auth.registerForm'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/auth.tokenResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/auth.ApiError'
      security:
      - ApiKeyAuth: []
      summary: Auth
      tags:
      - Auth
  /user:
    get:
      description: get user info
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.userResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/user.errorResponse'
      security:
      - ApiKeyAuth: []
      summary: User
      tags:
      - Users
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
